Repository TeamShiksha/openlogo, pull requests merged in 2024-12, with the labels that each got.

#430 Implement Catalog Table with Pagination, Search, and Image Upload Modal
  packages/ui/src/assets/DragAndDropBg.svg
  packages/ui/src/assets/left-arrow.svg
  packages/ui/src/assets/right-arrow.svg
  packages/ui/src/components/admindashboard/Catalog.jsx
  packages/ui/src/components/admindashboard/Catalog.module.css
  packages/ui/src/components/admindashboard/CatalogItem.jsx
  packages/ui/src/components/admindashboard/CatalogItem.module.css
  packages/ui/src/components/admindashboard/ImageUploadModal.jsx
  packages/ui/src/components/admindashboard/ImageUploadModal.module.css
  packages/ui/src/components/common/modal/Modal.jsx
  packages/ui/src/components/common/modal/Modal.module.css
  packages/ui/src/utils/constants.js
Labels: enhancement

#440 Refactor Admin controller: Implement Repository Pattern and Update Routes for Monorepo
  packages/app/controllers/admin/add.js
  packages/app/controllers/admin/data.js
  packages/app/controllers/admin/reupload.js
  packages/app/controllers/admin/upload.js
  packages/app/middlewares/fileUpload.js
  packages/app/models/Images.js
  packages/app/repositories/Images.js
  packages/app/routes/admin.js
  packages/app/routes/index.js
  packages/app/services/Images.js
  packages/app/services/User.js
  packages/app/utils/cloudFront.js
Labels: refactor, high priority

#429 Refactor Business Controller: Implement Repository Pattern and Update Routes for Monorepo
  packages/app/controllers/business/logo.js
  packages/app/controllers/business/search.js
  packages/app/package.json
  packages/app/repositories/Images.js
  packages/app/repositories/Keys.js
  packages/app/repositories/Subscriptions.js
  packages/app/routes/business.js
  packages/app/routes/index.js
  packages/app/services/Images.js
  packages/app/services/Keys.js
  packages/app/services/Subscription.js
  packages/app/utils/cloudFront.js
Labels: enhancement, refactor, high priority

#462 Features section css updated
  packages/ui/package.json
  packages/ui/src/assets/database.svg
  packages/ui/src/assets/rapid.svg
  packages/ui/src/assets/search.svg
  packages/ui/src/components/features/Features.jsx
  packages/ui/src/components/features/Features.module.css
Labels: low priority

#451 Add About Us section
  packages/ui/src/assets/bitbucket.png
  packages/ui/src/assets/confluence.png
  packages/ui/src/assets/discord.png
  packages/ui/src/assets/dropbox.png
  packages/ui/src/assets/figma.png
  packages/ui/src/assets/g_calendar.png
  packages/ui/src/assets/google_drive.png
  packages/ui/src/assets/intercom.png
  packages/ui/src/assets/jira.png
  packages/ui/src/assets/mailchimp.png
  packages/ui/src/assets/notion.png
  packages/ui/src/assets/slack.png
  packages/ui/src/assets/stripe.png
  packages/ui/src/assets/whatsapp.png
  packages/ui/src/assets/zapier.png
  packages/ui/src/assets/zendesk.png
  packages/ui/src/components/about/About.jsx
  packages/ui/src/components/about/About.module.css
  packages/ui/src/components/demo/Demo.module.css
  packages/ui/src/pages/home/Home.jsx
  packages/ui/src/utils/color.css
  packages/ui/src/utils/constants.js
Labels: enhancement

#468 fixed text size of Feature and About section
  packages/ui/src/components/about/About.module.css
  packages/ui/src/components/features/Features.module.css
  packages/ui/src/pages/home/Home.jsx
Labels: bug

#471 Fix: customInput component
  packages/ui/src/components/common/input/CustomInput.jsx
  packages/ui/src/components/common/input/CustomInput.module.css
Labels: bug

#472 fixed alignment of pricing section
  packages/ui/components/pricing/Pricing.module.css
  packages/ui/components/pricing/PricingCard.module.css
Labels: bug

#475 Reinstate the user interface for the FAQ section.
  packages/ui/src/assets/minusCircle.svg
  packages/ui/src/assets/plusCircle.svg
  packages/ui/src/components/faqs/FAQs.jsx
  packages/ui/src/components/faqs/FAQs.module.css
  packages/ui/src/pages/home/Home.jsx
Labels: bug

#469 Update CloudFormation Template to Add IAM Group with Read-Only Permissions
  packages/app/aws/cloudformation_dev_test.yml
Labels: enhancement, good first issue, low priority
