Repository TeamShiksha/openlogo, pull requests merged in 2025-07, with the labels that each got.

#748 Corrected background image path in HeroSection for production
  packages/ui/src/components/hero/HeroSection.module.css
Labels: bug

#759 fix: demo search logo ui
  packages/ui/__tests__/components/Demo.test.jsx
  packages/ui/src/components/demo/Demo.jsx
Labels: enhancement

#760 catalog api integration for logo upload & reupload
  packages/ui/__tests__/components/Catalog.test.jsx
  packages/ui/__tests__/components/CatalogItem.test.jsx
  packages/ui/src/components/admin/AdminDashboard.jsx
  packages/ui/src/components/catalog/Catalog.jsx
  packages/ui/src/components/catalog/Catalog.module.css
  packages/ui/src/components/catalog/CatalogItem.jsx
  packages/ui/src/components/catalog/ImageUploadModal.jsx
  packages/ui/src/components/catalog/ImageUploadModal.module.css
  packages/ui/src/components/common/modal/Modal.jsx
  packages/ui/src/hooks/useApi.js
  packages/ui/src/page/dashboard/Dashboard.jsx
  packages/ui/src/utils/Constants.js
Labels: enhancement

#769 Remove ENDPOINTS.md from docs folder and place it inside DEVELOPMENT.md
  docs/DEVELOPMENT.md
  docs/ENDPOINTS.md
Labels: documentation
