Repository TeamShiksha/openlogo, pull requests merged in 2025-06, with the labels that each got.

#690 fix: show active page highlight in navbar
  packages/ui/__tests__/components/common/ScrollManager.test.jsx
  packages/ui/src/components/header/Header.jsx
  packages/ui/src/components/header/Header.module.css
  packages/ui/src/components/header/MobileHeaderMenu.jsx
  packages/ui/src/components/header/MobileHeaderMenu.module.css
  packages/ui/src/utils/Constants.js
  packages/ui/src/utils/Helpers.js
Labels: enhancement

#693 fix: auth UI state issues & dynamic footer year
  packages/ui/__tests__/components/Footer.test.jsx
  packages/ui/__tests__/components/auth/Signup.test.jsx
  packages/ui/src/components/auth/Signin.jsx
  packages/ui/src/components/auth/Signup.jsx
  packages/ui/src/components/footer/Footer.jsx
Labels: bug

#667 Enhancement/661 api key generation and deletion
  packages/app/__tests__/controllers/users/deleteapikey.js
  packages/app/controllers/users.js
  packages/ui/__tests__/components/auth/Auth.test.jsx
  packages/ui/__tests__/components/dashboard/ApiKeyForm.test.jsx
  packages/ui/__tests__/components/dashboard/DeleteKeyModal.test.jsx
  packages/ui/__tests__/page/dashboard/Dashboard.test.jsx
  packages/ui/public/copy-icon.svg
  packages/ui/src/components/common/modal/Modal.jsx
  packages/ui/src/components/common/table/Table.jsx
  packages/ui/src/components/dashboard/DeleteKeyModal.jsx
  packages/ui/src/components/dashboard/DeleteKeyModal.module.css
  packages/ui/src/components/dashboard/apikeyform/ApiKeyForm.jsx
  packages/ui/src/components/dashboard/apikeyform/ApiKeyForm.module.css
  packages/ui/src/components/demo/Demo.jsx
  packages/ui/src/components/toast/Toast.module.css
  packages/ui/src/page/dashboard/Dashboard.jsx
  packages/ui/src/page/dashboard/Dashboard.module.css
  packages/ui/src/utils/Constants.js
Labels: enhancement

#697 Integrate stats API on frontend, fix: backend JSON response structure
  docs/ENDPOINTS.md
  packages/app/__tests__/controllers/catalog/analytics.js
  packages/app/controllers/catalog.js
  packages/app/utils/mocks.js
  packages/ui/__tests__/components/analytics/Analytics.test.jsx
  packages/ui/src/components/analytics/Analytics.jsx
  packages/ui/src/components/analytics/AnalyticsCard.jsx
Labels: enhancement

#701 691: added toast message for every api call in packages/ui
  packages/ui/__tests__/components/auth/Signin.test.jsx
  packages/ui/__tests__/components/dashboard/settings/DeleteAccount.test.jsx
  packages/ui/__tests__/components/dashboard/userinfo/UserInfo.test.jsx
  packages/ui/__tests__/contexts/AuthContext.test.jsx
  packages/ui/__tests__/contexts/OperatorContext.test.jsx
  packages/ui/__tests__/contexts/UserContext.test.jsx
  packages/ui/__tests__/page/dashboard/Dashboard.test.jsx
  packages/ui/src/components/auth/Signin.jsx
  packages/ui/src/components/auth/Signup.jsx
  packages/ui/src/components/dashboard/DeleteKeyModal.jsx
  packages/ui/src/components/dashboard/settingpage/DeleteAccountConfirmationModal.jsx
  packages/ui/src/components/dashboard/userinfo/UserInfo.jsx
  packages/ui/src/components/toast/Toast.jsx
  packages/ui/src/components/toast/Toast.module.css
  packages/ui/src/contexts/AuthContext.jsx
  packages/ui/src/contexts/OperatorContext.jsx
  packages/ui/src/contexts/UserContext.jsx
  packages/ui/src/main.jsx
  packages/ui/src/utils/Constants.js
Labels: enhancement

#708 Updated brand logos and modified Constant.js file
  packages/ui/src/assets/adobe.png
  packages/ui/src/assets/alphabet.png
  packages/ui/src/assets/amazon.png
  packages/ui/src/assets/apple.png
  packages/ui/src/assets/ford.png
  packages/ui/src/assets/ibm.png
  packages/ui/src/assets/mastercard.png
  packages/ui/src/assets/meta.png
  packages/ui/src/assets/microsoft.png
  packages/ui/src/assets/nike.png
  packages/ui/src/assets/nvidia.png
  packages/ui/src/assets/salesforce.png
  packages/ui/src/assets/target.png
  packages/ui/src/assets/tesla.png
  packages/ui/src/assets/united_healthcare.png
  packages/ui/src/assets/walmart.png
  packages/ui/src/utils/Constants.js
Labels: enhancement

#699 687: API Integration to /verify
  packages/app/__tests__/controllers/auth/verify.js
  packages/app/controllers/auth.js
  packages/app/repositories/usertoken.js
  packages/app/routes/index.js
  packages/app/services/usertoken.js
  packages/ui/src/components/verification/VerifyEmail.css
  packages/ui/src/components/verification/VerifyEmail.jsx
Labels: enhancement

#722 fix responsiveness of dropdown component and align it with the theme of the project
  packages/ui/src/components/common/dropdown/Dropdown.module.css
Labels: bug

#732 Ensure single FAQ expansion
  packages/ui/src/components/faqs/FAQs.jsx
Labels: enhancement

#721 712 refactor the verification page
  packages/app/utils/constants.js
  packages/ui/__tests__/components/verification/VerifyEmail.test.jsx
  packages/ui/src/App.jsx
  packages/ui/src/components/verification/VerifyEmail.css
  packages/ui/src/components/verification/VerifyEmail.jsx
  packages/ui/src/page/verification/Verification.jsx
  packages/ui/src/page/verification/Verification.module.css
Labels: refactor

#733 fix: dashboard loading spinner, dashboard spacing
  packages/ui/__tests__/page/dashboard/Dashboard.test.jsx
  packages/ui/src/components/common/dropdown/Dropdown.module.css
  packages/ui/src/page/dashboard/Dashboard.jsx
  packages/ui/src/page/dashboard/Dashboard.module.css
Labels: enhancement, refactor

#736 Refactor/confirmation modal
  packages/ui/__tests__/components/ConfirmationModal.test.jsx
  packages/ui/__tests__/components/DeleteAccount.test.jsx
  packages/ui/__tests__/components/DeleteKeyModal.test.jsx
  packages/ui/__tests__/components/SettingCard.test.jsx
  packages/ui/__tests__/page/dashboard/Dashboard.test.jsx
  packages/ui/src/components/common/button/Button.jsx
  packages/ui/src/components/common/input/CustomInput.jsx
  packages/ui/src/components/common/table/Table.jsx
  packages/ui/src/components/confirm/ConfirmationModal.jsx
  packages/ui/src/components/confirm/ConfirmationModal.module.css
  packages/ui/src/components/confirm/DeleteKeyModal.jsx
  packages/ui/src/components/confirm/DeleteKeyModal.module.css
  packages/ui/src/components/settings/DeleteAccountConfirmationModal.jsx
  packages/ui/src/components/settings/SettingCard.jsx
  packages/ui/src/page/dashboard/Dashboard.jsx
  packages/ui/src/page/dashboard/Dashboard.module.css
  packages/ui/src/utils/Constants.js
Labels: refactor
