Repository TeamShiksha/openlogo, pull requests merged in 2025-02, with the labels that each got.

#538 table wrapper added in apidocs
  packages/ui/src/components/common/table/Table.module.css
  packages/ui/src/page/docs/Apidocs.jsx
  packages/ui/src/page/documentation/CodeBlock.jsx
  packages/ui/src/page/documentation/Documentation.jsx
  packages/ui/src/page/documentation/Documentation.module.css
  packages/ui/src/utils/Constants.js
Labels: refactor

#539 Refactor/514 add table dashboard
  packages/ui/src/components/common/table/Table.jsx
  packages/ui/src/components/common/table/Table.module.css
  packages/ui/src/index.css
  packages/ui/src/page/dashboard/Dashboard.jsx
  packages/ui/src/page/dashboard/Dashboard.module.css
Labels: enhancement

#543 Validate Navigation Links in Header and Footer & Add Tests
  packages/ui/__tests__/Footer.test.jsx
  packages/ui/__tests__/Header.test.jsx
  packages/ui/package.json
  packages/ui/src/utils/Constants.js
  pnpm-lock.yaml
Labels: test

#553 Added Swagger Documentation
  packages/app/index.js
  packages/app/package.json
  packages/app/routes/users.js
  packages/app/utils/swagger.js
Labels: documentation, enhancement

#556 replaced a tag with Link and updated tests
  packages/ui/__tests__/Footer.test.jsx
  packages/ui/__tests__/Header.test.jsx
  packages/ui/__tests__/MobileHeaderMenu.test.jsx
  packages/ui/src/App.jsx
  packages/ui/src/components/about/About.jsx
  packages/ui/src/components/common/ScrollToTop.jsx
  packages/ui/src/components/demo/Demo.jsx
  packages/ui/src/components/features/Features.jsx
  packages/ui/src/components/footer/Footer.jsx
  packages/ui/src/components/header/Header.jsx
  packages/ui/src/components/hero/HeroSection.jsx
  packages/ui/src/components/pricing/Pricing.jsx
  packages/ui/src/page/privacypolicy/PrivacyPolicy.module.css
  packages/ui/src/utils/Constants.js
  packages/ui/src/utils/Helpers.js
Labels: bug

#557 Created backend and frontend deploy files
  .github/workflows/deploy-backend.yaml
  .github/workflows/deploy-frontend.yaml
Labels: enhancement

#546 test: wrote test cases for Auth, Signin and Signup component
  packages/ui/__tests__/Auth.test.jsx
  packages/ui/__tests__/Signin.test.jsx
  packages/ui/__tests__/Signup.test.jsx
Labels: test

#577 Optimization for github workflows and husky
  .github/workflows/codeql.yml
  .github/workflows/deploy-backend.yaml
  .github/workflows/deploy-frontend.yaml
  .github/workflows/pre-commit.yaml
  .husky/pre-commit
Labels: bug

#580 Add tests for auth controllers
  packages/app/__tests__/controller/auth/forgot-password.js
  packages/app/__tests__/controller/auth/reset-password-session.js
  packages/app/__tests__/controller/auth/reset-password.js
  packages/app/__tests__/controller/auth/signin.js
  packages/app/__tests__/controller/auth/signout.js
  packages/app/__tests__/controller/auth/signup.js
  packages/app/__tests__/controller/auth/verify.js
  packages/app/controllers/auth.js
  packages/app/models/request.js
  packages/app/models/users.js
  packages/app/routes/auth.js
  packages/app/utils/testconstants.js
Labels: enhancement, test

#575 Navigation fixed for mobile view, footer navigations modified
  packages/ui/__tests__/Features.test.jsx
  packages/ui/__tests__/Footer.test.jsx
  packages/ui/__tests__/Header.test.jsx
  packages/ui/__tests__/MobileHeaderMenu.test.jsx
  packages/ui/__tests__/ScrollManager.test.jsx
  packages/ui/src/App.jsx
  packages/ui/src/components/common/ScrollManager.jsx
  packages/ui/src/components/common/ScrollToTop.jsx
  packages/ui/src/components/footer/Footer.jsx
  packages/ui/src/components/footer/Footer.module.css
  packages/ui/src/components/header/Header.jsx
  packages/ui/src/components/header/Header.module.css
  packages/ui/src/components/header/MobileHeaderMenu.jsx
  packages/ui/src/components/hero/HeroSection.jsx
  packages/ui/src/page/privacypolicy/PrivacyPolicy.jsx
  packages/ui/src/utils/Constants.js
  packages/ui/src/utils/Helpers.js
Labels: bug, enhancement
