Repository TeamShiksha/openlogo, pull requests merged in 2025-03, with the labels that each got.

#586 Add Privacy Policy component and related tests; update footer styles and constants
  .gitignore
  packages/ui/__tests__/page/PrivacyPolicy.test.jsx
  packages/ui/src/components/footer/Footer.module.css
  packages/ui/src/page/privacypolicy/PrivacyPolicy.jsx
  packages/ui/src/utils/Constants.js
Labels: enhancement

#591 Bug/583 ubuntu version upgrade
  .github/workflows/pre-commit.yaml
  packages/app/jest-mongodb-config.js
Labels: bug, enhancement, good first issue, help wanted

#589 Add test for pricing, pricingCard component and fix: test for feature component
  packages/ui/__tests__/components/Features.test.jsx
  packages/ui/__tests__/components/Pricing.test.jsx
  packages/ui/__tests__/components/PricingCard.test.jsx
Labels: test

#590 Documentation page: added unit test cases; refactored component by moving texts to constants, added dynamic URL and ContactForm Modal
  packages/app/eslint.config.mjs
  packages/ui/__tests__/page/PrivacyPolicy.test.jsx
  packages/ui/__tests__/page/documentation/CodeBlock.test.jsx
  packages/ui/__tests__/page/documentation/Documentation.test.jsx
  packages/ui/eslint.config.js
  packages/ui/src/page/documentation/CodeBlock.jsx
  packages/ui/src/page/documentation/Documentation.jsx
  packages/ui/src/page/documentation/Documentation.module.css
  packages/ui/src/page/privacypolicy/PrivacyPolicy.jsx
  packages/ui/src/utils/Constants.js
  packages/ui/src/utils/Helpers.js
Labels: enhancement, refactor, test

#603 Enhancement: Enable Submit button when all the input fields are valid
  packages/ui/__tests__/components/auth/Signin.test.jsx
  packages/ui/__tests__/components/auth/Signup.test.jsx
  packages/ui/__tests__/components/contact/ContactForm.test.jsx
  packages/ui/__tests__/components/contact/GetInTouch.test.jsx
  packages/ui/src/components/auth/Signin.jsx
  packages/ui/src/components/auth/Signup.jsx
  packages/ui/src/components/common/input/CustomInput.jsx
  packages/ui/src/components/common/input/CustomInput.module.css
  packages/ui/src/components/contact/ContactForm.jsx
  packages/ui/src/components/contact/ContactForm.module.css
  packages/ui/src/utils/Helpers.js
Labels: enhancement, test

#605 Enhancement/596 check protected routes and context
  packages/ui/__tests__/components/common/ScrollManager.test.jsx
  packages/ui/__tests__/contexts/AuthContext.test.jsx
  packages/ui/__tests__/contexts/OperatorContext.test.jsx
  packages/ui/__tests__/contexts/UserContext.test.jsx
  packages/ui/__tests__/utils/ProtectedRoute.test.jsx
  packages/ui/src/App.jsx
  packages/ui/src/utils/ProtectedRoute.jsx
Labels: enhancement

#597 added rate-limit for public route fix #592
  packages/app/middlewares/rateLimiter.js
  packages/app/package.json
  packages/app/routes/index.js
Labels: bug

#613 Consistent UI in admin route with test cases
  packages/ui/__tests__/components/Catalog.test.jsx
  packages/ui/__tests__/components/CatalogItem.test.jsx
  packages/ui/src/components/admindashboard/Catalog.jsx
  packages/ui/src/components/admindashboard/Catalog.module.css
  packages/ui/src/components/admindashboard/CatalogItem.jsx
  packages/ui/src/components/admindashboard/CatalogItem.module.css
Labels: enhancement

#612 feat(#599): Add Analytics Component to Admin.jsx
  packages/ui/__tests__/components/analytics/Analytics.test.jsx
  packages/ui/__tests__/components/analytics/AnalyticsCard.test.jsx
  packages/ui/__tests__/page/admin/Admin.test.jsx
  packages/ui/src/App.jsx
  packages/ui/src/components/admindashboard/Catalog.jsx
  packages/ui/src/components/admindashboard/Catalog.module.css
  packages/ui/src/components/analytics/Analytics.jsx
  packages/ui/src/components/analytics/Analytics.module.css
  packages/ui/src/components/analytics/AnalyticsCard.jsx
  packages/ui/src/components/analytics/AnalyticsCard.module.css
  packages/ui/src/page/admin/Admin.jsx
  packages/ui/src/page/admin/Admin.module.css
  packages/ui/src/utils/Constants.js
  packages/ui/vitest.config.js
Labels: enhancement
