Repository TeamShiksha/openlogo, pull requests merged in 2025-05, with the labels that each got.

#640 615 integrating getuserinfo api
  packages/ui/__tests__/components/Footer.test.jsx
  packages/ui/__tests__/components/Header.test.jsx
  packages/ui/__tests__/components/HeroSection.test.jsx
  packages/ui/__tests__/components/PricingCard.test.jsx
  packages/ui/__tests__/components/auth/Auth.test.jsx
  packages/ui/__tests__/components/auth/Signin.test.jsx
  packages/ui/__tests__/components/dashboard/usage/Usage.test.jsx
  packages/ui/__tests__/components/dashboard/userinfo/UserInfo.test.jsx
  packages/ui/__tests__/contexts/UserContext.test.jsx
  packages/ui/__tests__/page/Home.test.jsx
  packages/ui/__tests__/page/dashboard/Dashboard.test.jsx
  packages/ui/src/components/auth/Signin.jsx
  packages/ui/src/components/common/input/CustomInput.jsx
  packages/ui/src/components/dashboard/changepassword/ChangePassword.jsx
  packages/ui/src/components/dashboard/changepassword/ChangePassword.module.css
  packages/ui/src/components/dashboard/currentplan/CurrentPlan.jsx
  packages/ui/src/components/dashboard/currentplan/CurrentPlan.module.css
  packages/ui/src/components/dashboard/settingpage/SettingCard.jsx
  packages/ui/src/components/dashboard/settingpage/SettingCard.module.css
  packages/ui/src/components/dashboard/usage/Usage.jsx
  packages/ui/src/components/dashboard/usage/Usage.module.css
  packages/ui/src/components/dashboard/userinfo/UserInfo.jsx
  packages/ui/src/components/dashboard/userinfo/UserInfo.module.css
  packages/ui/src/components/header/Header.jsx
  packages/ui/src/components/hero/HeroSection.jsx
  packages/ui/src/components/pricing/Pricing.jsx
  packages/ui/src/components/pricing/PricingCard.jsx
  packages/ui/src/contexts/UserContext.jsx
  packages/ui/src/page/dashboard/Dashboard.jsx
  packages/ui/src/page/dashboard/Dashboard.module.css
  packages/ui/src/page/home/Home.jsx
  packages/ui/src/utils/Constants.js
Labels: enhancement

#641 Search functionality added and FAQs modified
  packages/ui/__tests__/components/Demo.test.jsx
  packages/ui/src/components/demo/Demo.jsx
  packages/ui/src/components/demo/Demo.module.css
  packages/ui/src/page/home/Home.jsx
  packages/ui/src/utils/Constants.js
Labels: enhancement

#637 Signout Integration
  packages/ui/__tests__/contexts/AuthContext.test.jsx
  packages/ui/__tests__/page/dashboard/Dashboard.test.jsx
  packages/ui/src/contexts/AuthContext.jsx
  packages/ui/src/page/dashboard/Dashboard.jsx
  packages/ui/src/page/dashboard/Dashboard.module.css
  packages/ui/src/utils/Constants.js
Labels: enhancement

#644 Enhancement: Integrate ContactForm with api; add tests
  packages/ui/__tests__/components/contact/ContactForm.test.jsx
  packages/ui/src/components/common/input/CustomInput.jsx
  packages/ui/src/components/contact/ContactForm.jsx
  packages/ui/src/components/contact/ContactForm.module.css
  packages/ui/src/index.css
  packages/ui/src/utils/Constants.js
  packages/ui/src/utils/Helpers.js
Labels: enhancement, test

#614 Guest Sign In Feature Implementation
  packages/app/__tests__/controllers/auth/signin.js
  packages/app/controllers/auth.js
  packages/app/models/index.js
  packages/app/repositories/index.js
  packages/app/repositories/users.js
  packages/app/schemas/auth.js
  packages/app/services/users.js
  packages/app/utils/constants.js
  packages/app/utils/mocks.js
  packages/ui/__tests__/components/auth/Signup.test.jsx
  packages/ui/src/App.jsx
  packages/ui/src/components/auth/SignForm.module.css
  packages/ui/src/components/auth/Signin.jsx
  packages/ui/src/components/common/table/Table.jsx
  packages/ui/src/components/dashboard/apikeyform/ApiKeyForm.jsx
  packages/ui/src/components/dashboard/changepassword/ChangePassword.jsx
  packages/ui/src/components/dashboard/currentplan/CurrentPlan.jsx
  packages/ui/src/components/dashboard/settingpage/SettingCard.jsx
  packages/ui/src/components/dashboard/userinfo/UserInfo.jsx
  packages/ui/src/contexts/AuthContext.jsx
  packages/ui/src/page/dashboard/Dashboard.jsx
  packages/ui/src/utils/Constants.js
Labels: enhancement, poc

#648 Add companyUri and extension to image upload functionality
  packages/app/__tests__/controllers/catalog/addlogo.js
  packages/app/controllers/catalog.js
  packages/app/models/images.js
  packages/app/schemas/catalog.js
  packages/app/services/images.js
Labels: enhancement, refactor

#654 Demo search api created and integrated
  packages/app/__tests__/controllers/logo/demo-search.js
  packages/app/controllers/logo.js
  packages/app/routes/index.js
  packages/app/routes/logo.js
  packages/app/schemas/catalog.js
  packages/ui/__tests__/components/Demo.test.jsx
  packages/ui/src/components/demo/Demo.jsx
  packages/ui/src/utils/Helpers.js
Labels: enhancement

#659 Add Custom Reusable Loading Spinner
  packages/ui/__tests__/components/auth/Signin.test.jsx
  packages/ui/__tests__/components/auth/Signup.test.jsx
  packages/ui/src/components/auth/Signin.jsx
  packages/ui/src/components/auth/Signup.jsx
  packages/ui/src/components/common/button/Button.jsx
  packages/ui/src/components/common/button/Button.module.css
  packages/ui/src/components/common/loadingspinner/LoadingSpinner.jsx
  packages/ui/src/components/common/loadingspinner/LoadingSpinner.module.css
  packages/ui/src/page/dashboard/Dashboard.jsx
Labels: enhancement

#664 feat: implement user info update functionality with API integration and loading state
  packages/ui/__tests__/components/dashboard/userinfo/UserInfo.test.jsx
  packages/ui/src/components/dashboard/userinfo/UserInfo.jsx
Labels: enhancement, good first issue

#642 Forgot Password Feature for Sign-In Form
  packages/ui/__tests__/components/auth/Signin.test.jsx
  packages/ui/src/components/auth/Signin.jsx
  packages/ui/src/utils/Constants.js
Labels: enhancement

#666 Improve footer logo and documentation button navigation
  packages/ui/__tests__/components/Footer.test.jsx
  packages/ui/__tests__/components/HeroSection.test.jsx
  packages/ui/src/components/footer/Footer.jsx
  packages/ui/src/components/footer/Footer.module.css
  packages/ui/src/components/hero/HeroSection.jsx
Labels: enhancement

#655 Verification Component Integration with responsive alignment and tests
  packages/ui/__tests__/components/verification/VerifyEmail.test.jsx
  packages/ui/src/App.jsx
  packages/ui/src/components/verification/VerifyEmail.css
  packages/ui/src/components/verification/VerifyEmail.jsx
  packages/ui/src/utils/Constants.js
Labels: enhancement

#673 662 remove hard coded passwords from entire test suite
  package.json
  packages/app/__tests__/controllers/auth/reset-password.js
  packages/app/__tests__/controllers/auth/signup.js
  packages/app/__tests__/controllers/users/updatepassword.js
  packages/app/utils/generatePassword.js
  packages/app/utils/testconstants.js
Labels: bug, refactor

#672 656 optimize dockerfile and automate publishing to dockerhub
  packages/app/.dockerignore
  packages/app/Dockerfile
  packages/app/utils/generatePassword.js
  packages/ui/src/contexts/AuthContext.jsx
Labels: enhancement

#676 Fix: Issue #669 - Prevent message input from growing beyond the viewport on vertical resize in the Contact Us form
  packages/ui/src/components/contact/ContactForm.module.css
Labels: bug, refactor

#677 Toast component created
  packages/ui/__tests__/components/Toast.test.jsx
  packages/ui/__tests__/components/auth/Auth.test.jsx
  packages/ui/__tests__/components/auth/Signin.test.jsx
  packages/ui/__tests__/contexts/ToastContext.test.jsx
  packages/ui/src/components/auth/Signin.jsx
  packages/ui/src/components/toast/Toast.jsx
  packages/ui/src/components/toast/Toast.module.css
  packages/ui/src/contexts/Contexts.jsx
  packages/ui/src/contexts/ToastContext.jsx
  packages/ui/src/hooks/useToast.js
  packages/ui/src/main.jsx
Labels: enhancement

#688 Fix Footer Branding Text and Toast Test running Infinite loop
  packages/ui/__tests__/components/Toast.test.jsx
  packages/ui/src/components/footer/Footer.module.css
Labels: bug

#694 Fix Add Image Button
  packages/ui/src/components/admindashboard/ImageUploadModal.jsx
  packages/ui/src/components/admindashboard/ImageUploadModal.module.css
Labels: enhancement
