Repository TeamShiksha/openlogo, pull requests merged in 2025-08, with the labels that each got.

#777 Broken image shown in demo when searched
  packages/app/services/images.js
  packages/ui/__tests__/components/Demo.test.jsx
  packages/ui/src/components/catalog/ImageUploadModal.jsx
  packages/ui/src/components/demo/Demo.jsx
  packages/ui/src/components/demo/Demo.module.css
  packages/ui/src/utils/Constants.js
Labels: bug

#776 /users/me api route refactor to /user
  docs/DEVELOPMENT.md
  docs/Postman Collection/postman_collection.json
  packages/app/__tests__/controllers/users/createapikey.js
  packages/app/__tests__/controllers/users/deleteaccount.js
  packages/app/__tests__/controllers/users/deleteapikey.js
  packages/app/__tests__/controllers/users/getuserdata.js
  packages/app/__tests__/controllers/users/logorequest.js
  packages/app/__tests__/controllers/users/updatepassword.js
  packages/app/__tests__/controllers/users/updateprofile.js
  packages/app/routes/index.js
  packages/app/routes/users.js
  packages/ui/__tests__/contexts/UserContext.test.jsx
  packages/ui/src/components/apikeyform/ApiKeyForm.jsx
  packages/ui/src/components/settings/SettingCard.jsx
  packages/ui/src/components/userinfo/UserInfo.jsx
  packages/ui/src/contexts/UserContext.jsx
  packages/ui/src/page/dashboard/Dashboard.jsx
Labels: enhancement

#779 Configure cookie options based on environment
  packages/app/controllers/auth.js
  packages/app/controllers/users.js
  packages/app/utils/constants.js
  packages/app/utils/envSchema.js
  packages/app/utils/sendEmail.js
Labels: enhancement

#782 Api flow diagram
  docs/DEVELOPMENT.md
Labels: documentation

#797 fix: demo logo shows broken image on search
  packages/app/services/images.js
Labels: bug

#773 test(services): add unit tests for services
  packages/app/__tests__/services/images.js
  packages/app/__tests__/services/keys.js
  packages/app/__tests__/services/subscriptions.js
  packages/app/__tests__/services/userTokens.js
  packages/app/__tests__/services/users.js
  packages/app/utils/mocks.js
Labels: test, javascript

#781 test(logo): add unit tests for logo controller
  packages/app/__tests__/controllers/logo/get-logo.js
  packages/app/__tests__/controllers/logo/search-logo.js
  packages/app/utils/mocks.js
Labels: enhancement

#799 fix: logo not found in business api
  packages/app/services/images.js
  packages/app/services/subscriptions.js
  packages/ui/src/utils/Constants.js
Labels: bug
